config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'page#home'

  resources :products, only: [:index, :show]  do
    resources :ratings, only: [:create]
    resources :product_comments, only: [:create]
  end

  get 'rules' => 'page#rules'

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                :integer          not null, primary key
#  attachable_id     :integer
#  attachable_type   :string(255)
#  position          :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  file_file_name    :string(255)
#  file_content_type :string(255)
#  file_file_size    :integer
#  file_updated_at   :datetime
#

class Image < ActiveRecord::Base

  has_attached_file :file, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/

  belongs_to :attachable, polymorphic: true, touch: true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  name        :string(255)
#  url         :string(255)
#  description :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  round_id    :integer
#  best        :boolean
#

class Product < ActiveRecord::Base

  validates :name, :description, presence: true
  validates :url, format: URI::regexp(%w(http https))

  belongs_to :user
  belongs_to :round
  has_many :ratings
  has_many :images, as: :attachable, dependent: :destroy
  has_many :comments, class_name: 'ProductComment', dependent: :destroy

  accepts_nested_attributes_for :images ,:allow_destroy => true

  scope :bests, -> { where(best: true)}

  def scores
    ratings = self.ratings.to_a
    length = ratings.length
    return Hash.new(0.00) if length == 0
    [:design, :ux, :creative, :content, :average_value ].inject({}) {| result, k | result[k] = ratings.send(:sum, &:"#{k}").to_f/length; result }
  end

end

app/models/product_comment.rb
class ProductComment < ActiveRecord::Base
  belongs_to :product
end

app/models/rating.rb
# == Schema Information
#
# Table name: ratings
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  product_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  design     :integer          default("0")
#  ux         :integer          default("0")
#  creative   :integer          default("0")
#  content    :integer          default("0")
#

class Rating < ActiveRecord::Base

  FORM_LABELS = { design: '设计', ux: '交互', creative: '创意', content: '内容'}

  validates_presence_of :user, :product
  validates_uniqueness_of :user_id, scope: [:product_id]

  belongs_to :user
  belongs_to :product, touch: true

  # has_many :rating_values, dependent: :destroy

  # accepts_nested_attributes_for :rating_values

  scope :latest, -> {order("created_at desc")}
  scope :product_with_user, ->(product_id, user_id) { where(product_id: product_id, user_id: user_id)}

  def average_value
    (self.design + self.ux)*0.3 + (self.creative + self.content)*0.2
  end
end

app/models/rating_value.rb
# == Schema Information
#
# Table name: rating_values
#
#  rating_id  :integer
#  value      :float(24)        default("0")
#  rate_type  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class RatingValue < ActiveRecord::Base

  enum rate_type: [ :design, :ux, :creative, :content ]
  belongs_to :rating, touch: true
end

app/models/round.rb
# == Schema Information
#
# Table name: rounds
#
#  id       :integer          not null, primary key
#  start_at :datetime
#  end_at   :datetime
#

class Round < ActiveRecord::Base
  has_many :products, dependent: :nullify
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  failed_attempts        :integer          default("0"), not null
#  unlock_token           :string(255)
#  locked_at              :datetime
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :ratings
  has_many :products


  def rated_products
    self.ratings.pluck(:product_id)
  end

  def name
    email.to_s.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # for houndci test
  def testFunction
    foo = 1
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @round = Round.includes(:products).last
    @best_product = Product.where(best: true).last
    @rated_products = current_user.rated_products if current_user
  end
end

app/controllers/product_comments_controller.rb
class ProductCommentsController < ApplicationController

  def create
    comment = ProductComment.new(comment_params)
    comment.product_id = params[:product_id]
    comment.save
  end

  private

  def comment_params
    params.require(:product_comment).permit(:good, :bad, :feeling)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!

  def show
    @product = Product.includes(:ratings).find(params[:id])
    unless Rating.product_with_user(@product.id, current_user.id).any?
      redirect_to root_path, alert: '请先对该产品进行打分'
    end
    @product_statistics = @product.scores
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    @rating = Rating.new(rating_params)
    @rating.product_id = params[:product_id]
    @rating.user = current_user
    @rating.save
    render json: { :message => "打分成功" }
  end

  private
   def rating_params
    params.require(:rating).permit(:design, :ux, :creative, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.slim
doctype html

html lang=I18n.locale
  head
    title
      = "Zuiux"
    = stylesheet_link_tag   'application', media: 'all'
    /!
      | Favicons
      | \==================================================
    link href=image_url("favicon.png") rel=("shortcut icon") /
    link href=image_url("apple-touch-icon.png") rel="apple-touch-icon" /
    link href=image_url("apple-touch-icon-72x72.png") rel="apple-touch-icon" sizes="72x72" /
    link href=image_url("apple-touch-icon-114x114.png") rel="apple-touch-icon" sizes="114x114" /
    = csrf_meta_tags

  body data-user-id=current_user.try(:id)
    /!
      | MENU
      | \==================================================
    #menu-wrap.menu-back.cbp-af-header
      .section.boxed-width-menu
        .logo
        ul.slimmenu
          li
            = link_to '首页', root_path
          li
            = link_to '作品', products_path('html')
          li
            = link_to '规则', rules_path('html')
    = yield
    /!
      | FOOTER
      | \==================================================
    .footer-wrap.boxed-width
      .footer-social
        .container
          .sixteen.columns
            a data-dummy="twitter" href="#"  twitter
            a data-dummy="github" href="https://github.com/CSCStudio" target="_blank" github
            a data-dummy="facebook" href="#"  facebook
            a data-dummy=("google +") href="#"  google +
      .footer-credit
        .container
          .sixteen.columns
            p
              | © All rights reserved. Made by
              a data-dummy=("IG Design") href="http://CSCStudio.github.io"
                span CSC Studio
    = javascript_include_tag 'application'
    = yield :bottom

app/views/page/home.html.slim
/!
  | BLOG SECTION
  | \==================================================
- cache(@best_product) do
  #top.section.boxed-width.grey-background.padding-posts
    .container
      .eight.columns data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s")
        .post-top-text
          h4
            = @best_product.name
            br
            span.last-week-label
              | 本期最
              span UX
          .sub-line
          .sub-text
            span> 作者：
            = @best_product.user.try(:name)

      .eight.columns data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s")
        .post-top-text
          p.text-padding=@best_product.description
      .sixteen.columns data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s")
        .project-image-wrapper
          #owl-post-slider.owl-carousel.owl-theme
            - @best_product.images.each do |image|
              .item
                = image_tag image.file
/!
  | HOME SECTION
  | \==================================================
#home.section.home.boxed-width style="display:none;"
/!
  | ABOUT US SECTION
  | \==================================================
#about
  .section.boxed-width.grey-background.padding-top-bottom
    .container
      .sixteen.columns data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s")
        .header-section-text
          .sub-top 下期共4件作品
          h2 投票进行中
          .sub-line
      .sixteen.columns data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s")
        .about-carousel-wrap
          #sync1.owl-carousel
            .item
              p.text-padding 最UX是专业的设计团队和体验师平台。我们认为，影响一个网站的体验主要有四个核心因素：设计，交互，创意，内容。
              p 每周四中午12点，我们截止这一周的作品报名。我们会在接下来的几个小时里进行一轮初步的筛选，并在傍晚时分开始这一轮的投票。
              p 该轮投票将在下一个周二傍晚结束，并公布该轮最UX作品。
            .item
              p.text-padding 项目的优秀与否，要看大众的接受程度如何。而众多网站往往忽略这一点。闭门造车的傲娇，不如风风雨雨的考验。
              p 最UX的目标是建立一个让设计师可以更快获得更好的反馈，以此来完善自己的产品。
            .item
              p.text-padding 希望营造一个公平，公正，和谐的氛围。
              p 设计：和谐的色彩，适当的排列，文字与图片的搭配，等等。
              p 交互：页面跳转的流畅度，用户实现需求的效率，各元素的相关性，等等。
              p 创意：别具一格的风格等。创意是推动人类发展的关键。
              p 内容：光有漂亮的脸蛋显然是不够的。内容便是网站的内涵。
          #sync2.owl-carousel
            .item
              .line
              .line-ver
              .point-item
              p 关于投票
            .item
              .line
              .line-ver
              .point-item
              p 设计师
            .item
              .line
              .line-ver
              .point-item
              p 体验师
  /!
    | SEP. SECTION
    | \==================================================
  - @round.products.each do |product|
    - cache([product, current_user]) do
      .section.product.boxed-width.grey-background
        .cd-single-item
          .cd-slider-wrapper
            .cd-slider-cover
              a href=product.url target='_blank'
                i.fa.fa-chain
            ul.cd-slider
              li.selected
                = image_tag product.images.first.try(:file), alt: 'Product Image'
            /! cd-slider
          /! cd-slider-wrapper
          .cd-item-info data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s") data-product-id=product.id
            h5=product.name
            - if current_user && @rated_products.include?(product.id)
              .step-3
                p=product.description
                #ajax-form
                  .sub-line
                  = link_to product_path(product, 'html') do
                    button#send.send_message
                      span data-hover="submit"  参与讨论
            - else
              .step-1
                p=product.description
                #ajax-form
                  .sub-line
                  button.step-1-submit
                    span data-hover="submit"  我要投票
                  .status="已有#{product.ratings.count}票"
              .step-2 style='display:none'
                .vote-info
                  - Rating::FORM_LABELS.each do |attribute,label|
                    .skills-name=label
                    .pro-bar-container.pro-bar-margin
                      - 10.times do
                        .star
                      .point data-rate-type=attribute
                #ajax-form
                  .sub-line
                  button#send.send_message.step-2-submit
                    span data-hover="submit"  确定提交
              .step-3 style="display:none"
                p=product.description
                #ajax-form
                  .sub-line
                  = link_to product_path(product, 'html') do
                    button#send.send_message
                      span data-hover="submit"  参与讨论
        /! cd-item-info
/!
  | SEP. SECTION
  | \==================================================
.section.boxed-width.padding-top-bottom-parallax
  .parallax-sep-1
  .sep-background-mask
  .container
    = cache(:system_statistics, expires_in: 15.minutes)
      .four.columns
        .counter-wrap
          .counter-numb
            span.counter-facts=Product.bests.count
          .counter-line
          h6 期最佳UX
      .four.columns
        .counter-wrap
          .counter-numb
            span.counter-facts=Product.count
          .counter-line
          h6 份作品上传
      .four.columns
        .counter-wrap
          .counter-numb
            span.counter-facts=User.count
          .counter-line
          h6 人次参与
      .four.columns
        .counter-wrap
          .counter-numb
            span.counter-facts=Rating.count
          .counter-line
          h6 次投票

= content_for :bottom do
  coffee:
    "use strict"
    $('.step-1-submit').click (evt)->
      if Zuiux.current_user
        $item = $(evt.currentTarget).closest('.cd-item-info')
        $item.find('.step-1').hide()
        $item.find('.step-2').show()
      else
        location.href = "/users/sign_in"

    # 只用于演示，后面会去掉这部分内容
    $('.step-2-submit').click (evt)->
      $item = $(evt.currentTarget).closest('.cd-item-info')
      rating_values_attributes = []
      rating = {}
      $item.find('.point').each (index, el)->
        $el = $(el)
        rating[$el.data('rate-type')] = parseInt($el.text())
      $.ajax({
        type: "POST"
        url: "/products/#{$item.data('product-id')}/ratings"
        data:
          rating: rating
      }).success (data) =>
        $item.find('.step-2').hide()
        $item.find('.step-3').show()

    $('.star').hover (evt) ->
      $target = $(evt.currentTarget)
      $parent = $target.parent()
      index = $parent.find('.star').index($target)+1
      $parent.find(".star").removeClass('active')
      $parent.find(".star:lt(#{index})").addClass('active')
      $parent.find('.point').text(index)

app/views/page/products.html.slim
/!
  | HOME SECTION
  | \==================================================
#home.section.home.boxed-width style="display:none;"
/!
  | PORTFOLIO SECTION
  | \==================================================
#work
  .section.boxed-width.white-background.padding-posts
    .container
      .sixteen.columns data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s")
        .header-section-text
          .sub-top 向您展示
          h2 所有作品
          .sub-line
      .clear
      .portfolio
      .expander-wrap.relative
        #expander-wrap
          p.cls-btn
            a.close X
          .expander-inner
      .clear
      .sixteen.columns data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s")
        #portfolio-filter
          ul#filter
            li
              a.current data-filter="*" href="#" title=""  所有
            li
              a data-filter=".photography" href="#" title=""  最佳UX
            li
              a data-filter=".illustration" href="#" title=""  Illustration
            li
              a data-filter=".motion-graphics" href="#" title=""  Motion Graphics
            li
              a data-filter=".web-design" href="#" title=""  Web Design
    #projects-grid
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/18.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax slider
      a.expander href="product.html"
      .portfolio-box-1.illustration
        .mask-1
        img alt="" src=image_url("portfolio/30.jpg")
        h6 Dreamy Honey
        .line-mask
        p ajax video
      a.expander href="product.html"
      .portfolio-box-1.web-design
        .mask-1
        img alt="" src=image_url("portfolio/12.jpg")
        h6 Creative Zoe
        .line-mask
        p ajax gallery
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/19.jpg")
        h6 Crazy Layla
        .line-mask
        p external slider
      a href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/1.jpg")
        h6 Holy Sadie
        .line-mask
        p external video
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/24.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax gallery
      a.expander href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/2.jpg")
        h6 Crazy Layla
        .line-mask
        p ajax slider
      a.expander href="product.html"
      .portfolio-box-1.web-design
        .mask-1
        img alt="" src=image_url("portfolio/3.jpg")
        h6 Creative Zoe
        .line-mask
        p ajax video
      a href="product.html"
      .portfolio-box-1.illustration
        .mask-1
        img alt="" src=image_url("portfolio/10.jpg")
        h6 Dreamy Honey
        .line-mask
        p external slider
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/11.jpg")
        h6 Crazy Layla
        .line-mask
        p external video
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/5.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax slider
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/4.jpg")
        h6 Creative Zoe
        .line-mask
        p external slider
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/18.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax slider
      a.expander href="product.html"
      .portfolio-box-1.illustration
        .mask-1
        img alt="" src=image_url("portfolio/30.jpg")
        h6 Dreamy Honey
        .line-mask
        p ajax video
      a.expander href="product.html"
      .portfolio-box-1.web-design
        .mask-1
        img alt="" src=image_url("portfolio/12.jpg")
        h6 Creative Zoe
        .line-mask
        p ajax gallery
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/19.jpg")
        h6 Crazy Layla
        .line-mask
        p external slider
      a href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/1.jpg")
        h6 Holy Sadie
        .line-mask
        p external video
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/24.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax gallery
      a.expander href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/2.jpg")
        h6 Crazy Layla
        .line-mask
        p ajax slider
      a.expander href="product.html"
      .portfolio-box-1.web-design
        .mask-1
        img alt="" src=image_url("portfolio/3.jpg")
        h6 Creative Zoe
        .line-mask
        p ajax video
      a href="product.html"
      .portfolio-box-1.illustration
        .mask-1
        img alt="" src=image_url("portfolio/10.jpg")
        h6 Dreamy Honey
        .line-mask
        p external slider
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/11.jpg")
        h6 Crazy Layla
        .line-mask
        p external video
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/5.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax slider
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/4.jpg")
        h6 Creative Zoe
        .line-mask
        p external slider
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/18.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax slider
      a.expander href="product.html"
      .portfolio-box-1.illustration
        .mask-1
        img alt="" src=image_url("portfolio/30.jpg")
        h6 Dreamy Honey
        .line-mask
        p ajax video
      a.expander href="product.html"
      .portfolio-box-1.web-design
        .mask-1
        img alt="" src=image_url("portfolio/12.jpg")
        h6 Creative Zoe
        .line-mask
        p ajax gallery
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/19.jpg")
        h6 Crazy Layla
        .line-mask
        p external slider
      a href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/1.jpg")
        h6 Holy Sadie
        .line-mask
        p external video
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/24.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax gallery
      a.expander href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/2.jpg")
        h6 Crazy Layla
        .line-mask
        p ajax slider
      a.expander href="product.html"
      .portfolio-box-1.web-design
        .mask-1
        img alt="" src=image_url("portfolio/3.jpg")
        h6 Creative Zoe
        .line-mask
        p ajax video
      a href="product.html"
      .portfolio-box-1.illustration
        .mask-1
        img alt="" src=image_url("portfolio/10.jpg")
        h6 Dreamy Honey
        .line-mask
        p external slider
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/11.jpg")
        h6 Crazy Layla
        .line-mask
        p external video
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/5.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax slider
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/4.jpg")
        h6 Creative Zoe
        .line-mask
        p external slider
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/18.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax slider
      a.expander href="product.html"
      .portfolio-box-1.illustration
        .mask-1
        img alt="" src=image_url("portfolio/30.jpg")
        h6 Dreamy Honey
        .line-mask
        p ajax video
      a.expander href="product.html"
      .portfolio-box-1.web-design
        .mask-1
        img alt="" src=image_url("portfolio/12.jpg")
        h6 Creative Zoe
        .line-mask
        p ajax gallery
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/19.jpg")
        h6 Crazy Layla
        .line-mask
        p external slider
      a href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/1.jpg")
        h6 Holy Sadie
        .line-mask
        p external video
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/24.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax gallery
      a.expander href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/2.jpg")
        h6 Crazy Layla
        .line-mask
        p ajax slider
      a.expander href="product.html"
      .portfolio-box-1.web-design
        .mask-1
        img alt="" src=image_url("portfolio/3.jpg")
        h6 Creative Zoe
        .line-mask
        p ajax video
      a href="product.html"
      .portfolio-box-1.illustration
        .mask-1
        img alt="" src=image_url("portfolio/10.jpg")
        h6 Dreamy Honey
        .line-mask
        p external slider
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/11.jpg")
        h6 Crazy Layla
        .line-mask
        p external video
      a.expander href="product.html"
      .portfolio-box-1.photography
        .mask-1
        img alt="" src=image_url("portfolio/5.jpg")
        h6 Holy Sadie
        .line-mask
        p ajax slider
      a href="product.html"
      .portfolio-box-1.motion-graphics
        .mask-1
        img alt="" src=image_url("portfolio/4.jpg")
        h6 Creative Zoe
        .line-mask
        p external slider

app/views/product_comments/_item.html.slim
/! comments
.comment-wrapper
  .two.columns data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s")
    .team-wrap
      img alt="" src=image_url("team1.jpg")
      .comment-name
        h6 Alex Andrews
        p
          span founder
  .fourteen.columns.comment data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s")
    span.good 亮点
    p
      = comment.good
    span.bad 不足
    p
      = comment.bad
    span.feeling 感受
    p
      =simple_format comment.feeling
    .section-separator-line
      span.posted-time.timeago title=comment.created_at
      i.fa.fa-comment
      i.fa.fa-heart
      i.fa.fa-gavel
  .clear.break
/! replies
.comment-wrapper.reply
  .two.columns
  .fourteen.columns.comment data-scroll-reveal=("enter bottom move 100px over 0.6s after 0.2s")
    .avatar-wrap
      img alt="" src=image_url("team1.jpg")
      .comment-name
    p.name
      span> Alex Andrews
      | Founder
    p
      | Our team is specially designed to create successful, custom, innovative digital products from the initial concept through full product launch. From whiteboard sketches to pixel-perfect designs.
    .section-separator-line
      span.posted-time Posted: 3 days ago
      i.fa.fa-comment
  .clear.break